Document: libdatrie
Title: Debian libdatrie Manual
Author: <insert document author here>
Abstract: This manual describes what libdatrie is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libdatrie/libdatrie.sgml.gz

Format: postscript
Files: /usr/share/doc/libdatrie/libdatrie.ps.gz

Format: text
Files: /usr/share/doc/libdatrie/libdatrie.text.gz

Format: HTML
Index: /usr/share/doc/libdatrie/html/index.html
Files: /usr/share/doc/libdatrie/html/*.html
